apiVersion: v1
kind: Pod
metadata:
  name: devpod
spec:
  containers:
  - name: devpod
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      privileged: false
      runAsNonRoot: false
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
